import unreal, os, json
project_root=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src=os.path.join(project_root,"Saved","Tatra613ScenePreserved","Tatra613_ScenePreserved.glb")
root="/Game/Dev/Vehicles/Tatra613DesktopScene"
asset_tools=unreal.AssetToolsHelpers.get_asset_tools()

if unreal.EditorAssetLibrary.does_directory_exist(root):
    unreal.EditorAssetLibrary.delete_directory(root)

task=unreal.AssetImportTask()
task.filename=src
task.destination_path=root
task.automated=True
task.replace_existing=True
task.save=True
task.options=None
asset_tools.import_asset_tasks([task])
unreal.EditorAssetLibrary.save_directory(root,only_if_is_dirty=False,recursive=True)

all_assets=unreal.EditorAssetLibrary.list_assets(root,recursive=True,include_folder=False)
mesh_paths=[]
for path in all_assets:
    asset=unreal.load_asset(path)
    if asset and asset.get_class().get_name()=="StaticMesh":
        mesh_paths.append(str(path))
if len(mesh_paths)!=133:
    raise RuntimeError("Expected 133 source scene meshes after donor-wheel exclusion, got "+str(len(mesh_paths)))

glass_path=root+"/Common/M_PC_T613_GlassCheap"
glass=asset_tools.create_asset(
    "M_PC_T613_GlassCheap",root+"/Common",unreal.Material,unreal.MaterialFactoryNew())
if not glass:
    raise RuntimeError("Could not create glass material")
unreal.MaterialEditingLibrary.delete_all_material_expressions(glass)
color=unreal.MaterialEditingLibrary.create_material_expression(
    glass,unreal.MaterialExpressionConstant3Vector,-320,-40)
color.set_editor_property("constant",unreal.LinearColor(0.012,0.018,0.022,1.0))
opacity=unreal.MaterialEditingLibrary.create_material_expression(
    glass,unreal.MaterialExpressionConstant,-320,80)
opacity.set_editor_property("r",0.12)
unreal.MaterialEditingLibrary.connect_material_property(
    color,"",unreal.MaterialProperty.MP_EMISSIVE_COLOR)
unreal.MaterialEditingLibrary.connect_material_property(
    opacity,"",unreal.MaterialProperty.MP_OPACITY)
glass.set_editor_property("blend_mode",unreal.BlendMode.BLEND_TRANSLUCENT)
glass.set_editor_property("two_sided",True)
glass.set_editor_property("shading_model",unreal.MaterialShadingModel.MSM_UNLIT)
unreal.MaterialEditingLibrary.recompile_material(glass)
unreal.EditorAssetLibrary.save_loaded_asset(glass)

glass_meshes=[]
for path in mesh_paths:
    asset=unreal.load_asset(path)
    name=asset.get_name()
    if name=="t613_glass_material" or name.startswith("t613_glass_material_"):
        mats=asset.get_editor_property("static_materials")
        for material_index in range(len(mats)):
            asset.set_material(material_index, glass)
        unreal.EditorAssetLibrary.save_loaded_asset(asset)
        glass_meshes.append(name)
if len(glass_meshes)!=6:
    raise RuntimeError("Expected 6 glass meshes, got "+str(glass_meshes))

mesh_paths.sort()
manifest_dir=os.path.join(project_root,"Source","PinkCab","Private","Vehicle","Generated")
os.makedirs(manifest_dir,exist_ok=True)
manifest=os.path.join(manifest_dir,"PinkCabTatra613SceneMeshPaths.inl")
with open(manifest,"w",encoding="utf-8",newline="\n") as f:
    f.write("// Generated by scripts/import_tatra_scene_preserved.py\n")
    f.write("static const TCHAR* const GTatra613SceneMeshPaths[] = {\n")
    for path in mesh_paths:
        obj=path.split(".")[-1]
        f.write('    TEXT("'+path+'"),\n')
    f.write("};\n")

report={
 "root":root,
 "mesh_count":len(mesh_paths),
 "glass_meshes":glass_meshes,
 "mesh_paths":mesh_paths,
 "manifest":manifest,
}
out=os.path.join(project_root,"Saved","Tatra613DesktopScene_report.json")
with open(out,"w",encoding="utf-8") as f:
    json.dump(report,f,indent=2)
unreal.log("TATRA_SCENE_CANONICAL_OK meshes="+str(len(mesh_paths))+" glass="+str(glass_meshes))
unreal.log("TATRA_SCENE_MANIFEST="+manifest)
